#!/usr/bin/env python3
"""
Video Clip Extraction Script
Extract individual stroke clips from full match videos based on frame numbers
Adds temporal context (±1 second) around each stroke
"""

import os
import pandas as pd
import cv2
from pathlib import Path
from tqdm import tqdm
import numpy as np

# Paths
BASE_DIR = Path(__file__).resolve().parents[2]
RAW_VIDEOS_DIR = BASE_DIR / "data" / "raw_videos"
CLIPS_DIR = BASE_DIR / "data" / "processed" / "clips"
REPORTS_DIR = BASE_DIR / "outputs" / "reports"
STROKE_STATS_FILE = REPORTS_DIR / "stroke_statistics.csv"

# Configuration
TEMPORAL_CONTEXT_SECONDS = 1.0  # Add ±1 second around stroke
MIN_CLIP_DURATION_FRAMES = 15   # Minimum clip length (0.5 sec at 30fps)


def load_stroke_data():
    """Load stroke statistics generated by organize_data.py"""
    if not STROKE_STATS_FILE.exists():
        print(f"❌ ERROR: {STROKE_STATS_FILE} not found!")
        print("Please run organize_data.py first to generate stroke statistics.")
        return None

    strokes_df = pd.read_csv(STROKE_STATS_FILE)
    print(f"✅ Loaded {len(strokes_df)} strokes from {STROKE_STATS_FILE}")
    return strokes_df


def get_video_info(video_path):
    """Get video properties (fps, frame count)"""
    cap = cv2.VideoCapture(str(video_path))

    if not cap.isOpened():
        return None, None, None

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    cap.release()

    return fps, frame_count, (width, height)


def extract_clip(video_path, frame_num, output_path, fps, frame_count):
    """
    Extract a clip centered on frame_num with temporal context

    Args:
        video_path: Path to source video
        frame_num: Frame number of the stroke
        output_path: Path to save extracted clip
        fps: Video frame rate
        frame_count: Total frames in video

    Returns:
        True if successful, False otherwise
    """
    # Calculate frame range with temporal context
    context_frames = int(TEMPORAL_CONTEXT_SECONDS * fps)
    start_frame = max(0, int(frame_num - context_frames))
    end_frame = min(frame_count - 1, int(frame_num + context_frames))

    # Check minimum duration
    clip_duration = end_frame - start_frame
    if clip_duration < MIN_CLIP_DURATION_FRAMES:
        return False, "Clip too short"

    # Open video
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        return False, "Cannot open video"

    # Get video properties
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # Create video writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(str(output_path), fourcc, fps, (width, height))

    # Set to start frame
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    # Extract frames
    frames_written = 0
    for frame_idx in range(start_frame, end_frame + 1):
        ret, frame = cap.read()
        if not ret:
            break
        out.write(frame)
        frames_written += 1

    # Cleanup
    cap.release()
    out.release()

    return True, f"{frames_written} frames"


def extract_all_clips(strokes_df):
    """Extract clips for all strokes"""
    print("=" * 70)
    print("EXTRACTING VIDEO CLIPS")
    print("=" * 70)
    print()

    # Create output directory
    CLIPS_DIR.mkdir(parents=True, exist_ok=True)

    # Group by match to process videos efficiently
    matches_grouped = strokes_df.groupby(['match_id', 'match_name'])

    # Statistics
    total_strokes = len(strokes_df)
    successful_extractions = 0
    failed_extractions = 0
    skipped_no_video = 0

    extraction_log = []

    print(f"Processing {len(matches_grouped)} matches...")
    print()

    for (match_id, match_name), match_strokes in matches_grouped:
        # Find video file
        video_file = RAW_VIDEOS_DIR / f"{match_id:02d}.mp4"

        if not video_file.exists():
            print(f"⚠️  Match {match_id:2d}: Video not found ({video_file.name})")
            skipped_no_video += len(match_strokes)
            for _, stroke in match_strokes.iterrows():
                extraction_log.append({
                    'match_id': match_id,
                    'set_num': stroke['set_num'],
                    'rally': stroke['rally'],
                    'ball_round': stroke['ball_round'],
                    'stroke_type': stroke['stroke_type_english'],
                    'status': 'video_not_found',
                    'reason': f'Video file {video_file.name} not found'
                })
            continue

        # Get video info
        fps, frame_count, resolution = get_video_info(video_file)

        if fps is None:
            print(f"❌ Match {match_id:2d}: Cannot read video properties")
            failed_extractions += len(match_strokes)
            for _, stroke in match_strokes.iterrows():
                extraction_log.append({
                    'match_id': match_id,
                    'set_num': stroke['set_num'],
                    'rally': stroke['rally'],
                    'ball_round': stroke['ball_round'],
                    'stroke_type': stroke['stroke_type_english'],
                    'status': 'failed',
                    'reason': 'Cannot read video properties'
                })
            continue

        print(f"📹 Match {match_id:2d}: {match_name[:50]}")
        print(f"   Video: {video_file.name} | FPS: {fps:.1f} | Frames: {frame_count} | Resolution: {resolution}")
        print(f"   Strokes to extract: {len(match_strokes)}")

        # Process each stroke in this match
        match_success = 0
        match_failed = 0

        for idx, stroke in tqdm(match_strokes.iterrows(), total=len(match_strokes),
                                desc=f"   Extracting clips", leave=False):
            # Create clip filename
            clip_name = (f"{match_id:02d}_set{stroke['set_num']}_"
                        f"rally{int(stroke['rally'])}_ball{int(stroke['ball_round'])}_"
                        f"{stroke['stroke_type_english']}.mp4")
            clip_path = CLIPS_DIR / clip_name

            # Skip if already exists
            if clip_path.exists():
                successful_extractions += 1
                match_success += 1
                extraction_log.append({
                    'match_id': match_id,
                    'set_num': stroke['set_num'],
                    'rally': stroke['rally'],
                    'ball_round': stroke['ball_round'],
                    'stroke_type': stroke['stroke_type_english'],
                    'status': 'already_exists',
                    'clip_name': clip_name
                })
                continue

            # Extract clip
            success, message = extract_clip(
                video_file,
                stroke['frame_num'],
                clip_path,
                fps,
                frame_count
            )

            if success:
                successful_extractions += 1
                match_success += 1
                extraction_log.append({
                    'match_id': match_id,
                    'set_num': stroke['set_num'],
                    'rally': stroke['rally'],
                    'ball_round': stroke['ball_round'],
                    'stroke_type': stroke['stroke_type_english'],
                    'frame_num': stroke['frame_num'],
                    'status': 'success',
                    'clip_name': clip_name,
                    'details': message
                })
            else:
                failed_extractions += 1
                match_failed += 1
                extraction_log.append({
                    'match_id': match_id,
                    'set_num': stroke['set_num'],
                    'rally': stroke['rally'],
                    'ball_round': stroke['ball_round'],
                    'stroke_type': stroke['stroke_type_english'],
                    'frame_num': stroke['frame_num'],
                    'status': 'failed',
                    'reason': message
                })

        print(f"   ✅ Success: {match_success} | ❌ Failed: {match_failed}")
        print()

    # Save extraction log
    log_df = pd.DataFrame(extraction_log)
    log_file = REPORTS_DIR / "clip_extraction_log.csv"
    log_df.to_csv(log_file, index=False)

    # Print summary
    print("=" * 70)
    print("EXTRACTION SUMMARY")
    print("=" * 70)
    print(f"Total strokes: {total_strokes}")
    print(f"✅ Successfully extracted: {successful_extractions}")
    print(f"❌ Failed: {failed_extractions}")
    print(f"⚠️  Skipped (no video): {skipped_no_video}")
    print()

    success_rate = (successful_extractions / total_strokes * 100) if total_strokes > 0 else 0
    print(f"Success rate: {success_rate:.1f}%")
    print()

    # Breakdown by stroke type
    print("Extracted clips by stroke type:")
    success_df = log_df[log_df['status'].isin(['success', 'already_exists'])]
    if len(success_df) > 0:
        stroke_type_counts = success_df['stroke_type'].value_counts()
        for stroke_type, count in stroke_type_counts.items():
            print(f"  {stroke_type:10s}: {count:6d} clips")
    print()

    print(f"📁 Clips saved to: {CLIPS_DIR}")
    print(f"📊 Extraction log saved to: {log_file}")
    print()

    # Create metadata file
    if len(success_df) > 0:
        metadata = strokes_df.merge(
            success_df[['match_id', 'set_num', 'rally', 'ball_round', 'clip_name']],
            on=['match_id', 'set_num', 'rally', 'ball_round'],
            how='inner'
        )
        metadata_file = CLIPS_DIR / "clips_metadata.csv"
        metadata.to_csv(metadata_file, index=False)
        print(f"📋 Clips metadata saved to: {metadata_file}")

    return log_df


def main():
    """Main function"""
    print("\n")
    print("*" * 70)
    print("*" + " " * 68 + "*")
    print("*" + "  ITI123 Project: Video Clip Extraction".center(68) + "*")
    print("*" + " " * 68 + "*")
    print("*" * 70)
    print("\n")

    print("Configuration:")
    print(f"  Temporal context: ±{TEMPORAL_CONTEXT_SECONDS} seconds")
    print(f"  Minimum clip duration: {MIN_CLIP_DURATION_FRAMES} frames")
    print()

    # Load stroke data
    strokes_df = load_stroke_data()
    if strokes_df is None:
        return

    print(f"Strokes to process: {len(strokes_df)}")
    print(f"  Clear: {len(strokes_df[strokes_df['stroke_type_english'] == 'Clear'])}")
    print(f"  Smash: {len(strokes_df[strokes_df['stroke_type_english'] == 'Smash'])}")
    print()

    # Extract clips
    extraction_log = extract_all_clips(strokes_df)

    print("=" * 70)
    print("✅ CLIP EXTRACTION COMPLETE!")
    print("=" * 70)
    print()
    print("Next steps:")
    print("1. Review extracted clips in: data/processed/clips/")
    print("2. Check extraction log: outputs/reports/clip_extraction_log.csv")
    print("3. Proceed with pose estimation")
    print("4. Run: python src/data_processing/extract_poses.py")
    print()


if __name__ == "__main__":
    main()
